### ISSUE TITLE
Exception handling in the websocket path obfuscates the real error

### ISSUE THREAD

**Issue by ZombieAlex** [ZombieAlex/MFCAuto#16]
`Client._readWebSocketPacket` contains a blanket try/catch in the main packet processing loop that causes any uncaught exceptions downstream to be caught and then a new, less helpful, error thrown.

This makes debugging error reports from user scripts exceedingly difficult.

I'd added that error handler originally as a safeguard for bugs in the new Client WebSocket code, but now believe the saner thing to do is to completely remove that try/catch and let any unhandled exception propagate.

**Comment by infoberg03** [comment]
Great, thanks for this change. Now it is clear the error is with me, I solved the issue now, had an incorrect path for the logfile

[02:10:26] [DEBUG] entering logTopic with topic: Smile111|Love1111|Pantsoff0+shot|#6- Shot-2111/C2C-999|Spank-567|444-PM|200-Song|Wheel333/bigwheel1999|Hi-Lo299|SoloVid3999-GG6999|
fs.js:643
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string or Buffer
    at Object.fs.open (fs.js:643:11)
    at WriteStream.open (fs.js:2155:6)
    at new WriteStream (fs.js:2141:10)
    at Object.fs.createWriteStream (fs.js:2103:10)
    at logTopic (C:\mfc-node2\main.js:211:24)
    at Model.currModel.on (C:\mfc-node2\main.js:370:3)
    at emitThree (events.js:135:13)
    at Model.emit (events.js:216:7)
    at Model.<anonymous> (C:\mfc-node2\node_modules\MFCAuto\lib\Model.js:146:26)
    at Array.forEach (<anonymous>)
    at Model.merge (C:\mfc-node2\node_modules\MFCAuto\lib\Model.js:144:27)
    at Client._packetReceived (C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:99:43)
    at Client._readWebSocketPacket (C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:311:18)
    at Client._readWebSocketData (C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:47:14)
    at WebSocket.client.on (C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:654:34)
    at emitOne (events.js:115:13)
