### ISSUE TITLE
Login failed on reconnect

### ISSUE THREAD

**Issue by infoberg03** [ZombieAlex/MFCAuto#17]
Hi,

I just started to see this error occuring recently, seems to be getting more frequent.

[11/14/2017 - 23:34:52] Done, will search for new models in 60 second(s).
[11/14/2017 - 23:34:55] Server has not responded in over 2 minutes. Trying to reconnect now.
[11/14/2017 - 23:34:56] Disconnected from MyFreeCams.  Reconnecting in 15 seconds...
[11/14/2017 - 23:35:12] Connecting to MyFreeCams websocket server xchat105...
[11/14/2017 - 23:35:13] Login failed for user 'Guest57004' password 'quest'
C:\snapshot\1\node_modules\MFCAuto\lib\Client.js:285
                throw new Error(`Error handling websocket packet: \n\t${e}\n\t"${originalMessage}"`);
                ^

Error: Error handling websocket packet:
        Error: Login failed
        "1 0 322968559 1 0"
    at EventEmitter._readWebSocketPacket (C:\snapshot\1\node_modules\MFCAuto\lib\Client.js:285:23)
    at EventEmitter._readWebSocketData (C:\snapshot\1\node_modules\MFCAuto\lib\Client.js:41:14)
    at WebSocket.__dirname.connect.Promise.ensureServerConfigIsLoaded.then.client.on.client.on (C:\snapshot\1\node_modules\MFCAuto\lib\Client.js:616:34)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at Receiver.EventEmitter.setSocket.head._receiver.onmessage (C:\snapshot\1\node_modules\ws\lib\WebSocket.js:143:47)
    at Receiver.dataMessage (C:\snapshot\1\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (C:\snapshot\1\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (C:\snapshot\1\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (C:\snapshot\1\node_modules\ws\lib\Receiver.js:139:10)
    at Socket.EventEmitter.setSocket.head._ultron.on (C:\snapshot\1\node_modules\ws\lib\WebSocket.js:139:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

**Comment by ZombieAlex** [comment]
Looks like you've set the password to "quest" with a Q. The guest password should be "guest" with a G. Because of that, [this code](https://github.com/ZombieAlex/MFCAuto/blob/master/src/main/Client.ts#L993) is not doing what it would normally do when a guest connection disconnects and the username used for the reconnect is wrong.

**Comment by infoberg03** [comment]
hmmm, I did not notice that. I did not set it manually, that came from an EXE version, will contact the creator about it, thanks a lot!

**Comment by infoberg03** [comment]
hmmm, I did not notice that. I did not set it manually, that came from an EXE version, will contact the creator about it, thanks a lot!
